### ISSUE TITLE
Bug提出及新功能建議

### ISSUE THREAD

**Issue by Frenzied-Dog** [WavJaby/NCKUpp#2]
Bug: 顯示課表時無法正確顯示衝堂的部分 (未開啟「顯示預排」選項時)。

功能建議: 可以添加查看及移除預排課程的功能。

**Comment by WavJaby** [comment]
Bug: 了解，因為顯示預排跟一般課表使用不同的顯示方式，我沒有預料到實際課表會有衝堂的問題，會再進行修復

功能建議: 打開課表等待左下角搜尋結束後，點選灰色預排課程，右上角會有刪除預排的功能
不確定"可以添加查看"的功能試什麼意思，是說想要表格形式的列表嗎?

感謝您的回報，會盡快解決此問題

**Comment by Frenzied-Dog** [comment]
我原先想的是像選課網站上的「以列表檢視」，不過好像現在這樣就可以了？

*更正: 應該是說像是課程查詢的「關注列表」，但是是預排列表(同時可以看到餘額)。

**Comment by WavJaby** [comment]
Bug: 目前已修復，可以再嘗試看看

功能建議: 了解，我會找時間加入此功能
